#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use File::Spec;

my $manual = File::Spec->catfile( $FindBin::Bin, '..', 'SKILLS.md' );
open my $fh, '<:raw', $manual or die "Cannot read browser skill manual: $!\n";
print while <$fh>;
close $fh or die "Cannot close browser skill manual: $!\n";

__END__

=head1 NAME

browser.skills - Print the raw browser skill agent manual

=head1 SYNOPSIS

  d2 browser.skills

=cut
